version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cloudlinker_user
      POSTGRES_PASSWORD: Franklincito1005
      POSTGRES_DB: cloudlinker_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloudlinker_user -d cloudlinker_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://cloudlinker_user:Franklincito1005@db:5432/cloudlinker_db
      API_KEYS: clave1,clave2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  postgres_data:
 
